# **DATA REVIEW & CLEANSING**



*   Fixing Missing Value
*   Fixing Rows & Columns


*   Fixing datatypes
*   Fixing Invalid Values


*   Filtering Data
*   Downloading clean Data

### **Importing Required Libraries & Dataset**

In [ ]:
import pandas as pd

# Source- Kaggle, Dataset- Lending club loan dataset
# Official link -

path='/content/drive/MyDrive/loan.csv'

data=pd.read_csv(path)
data.head()

/tmp/ipykernel_1894/3190918308.py:8: DtypeWarning: Columns (47) have mixed types. Specify dtype option on import or set low_memory=False.
  data=pd.read_csv(path)

,id,member_id,loan_amnt,funded_amnt,funded_amnt_inv,term,int_rate,installment,grade,sub_grade,...,num_tl_90g_dpd_24m,num_tl_op_past_12m,pct_tl_nvr_dlq,percent_bc_gt_75,pub_rec_bankruptcies,tax_liens,tot_hi_cred_lim,total_bal_ex_mort,total_bc_limit,total_il_high_credit_limit
0,1077501,1296599,5000,5000,4975.0,36 months,10.65%,162.87,B,B2,...,NaN,NaN,NaN,NaN,0.0,0.0,NaN,NaN,NaN,NaN
1,1077430,1314167,2500,2500,2500.0,60 months,15.27%,59.83,C,C4,...,NaN,NaN,NaN,NaN,0.0,0.0,NaN,NaN,NaN,NaN
2,1077175,1313524,2400,2400,2400.0,36 months,15.96%,84.33,C,C5,...,NaN,NaN,NaN,NaN,0.0,0.0,NaN,NaN,NaN,NaN
3,1076863,1277178,10000,10000,10000.0,36 months,13.49%,339.31,C,C1,...,NaN,NaN,NaN,NaN,0.0,0.0,NaN,NaN,NaN,NaN
4,1075358,1311748,3000,3000,3000.0,60 months,12.69%,67.79,B,B5,...,NaN,NaN,NaN,NaN,0.0,0.0,NaN,NaN,NaN,NaN

In [ ]:
data.tail()

,member_id,loan_amnt,funded_amnt,funded_amnt_inv,term,int_rate,installment,grade,sub_grade,emp_title,...,verification_status,issue_d,loan_status,purpose,zip_code,addr_state,dti,pub_rec_bankruptcies,issuemonth,empl_length
39712,92174,2500,2500,1075.0,36,8.07,78.42,A,A4,FiSite Research,...,Not Verified,Jul-07,Fully Paid,home_improvement,802xx,CO,11.33,0.0,Jul-2021,4
39713,90607,8500,8500,875.0,36,10.28,275.38,C,C1,"Squarewave Solutions, Ltd.",...,Not Verified,Jul-07,Fully Paid,credit_card,274xx,NC,6.40,0.0,Jul-2021,3
39714,90390,5000,5000,1325.0,36,8.07,156.84,A,A4,Unknown,...,Not Verified,Jul-07,Fully Paid,debt_consolidation,017xx,MA,2.30,0.0,Jul-2021,0.5
39715,89243,5000,5000,650.0,36,7.43,155.38,A,A2,Unknown,...,Not Verified,Jul-07,Fully Paid,other,208xx,MD,3.72,0.0,Jul-2021,0.5
39716,86999,7500,7500,800.0,36,13.75,255.43,E,E2,Evergreen Center,...,Not Verified,Jun-07,Fully Paid,debt_consolidation,027xx,MA,14.29,0.0,Jun-2021,0.5

In [ ]:
data.info(verbose=True)

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 39717 entries, 0 to 39716
Data columns (total 111 columns):
 #    Column                          Dtype
---   ------                          -----
 0    id                              int64
 1    member_id                       int64
 2    loan_amnt                       int64
 3    funded_amnt                     int64
 4    funded_amnt_inv                 float64
 5    term                            object
 6    int_rate                        object
 7    installment                     float64
 8    grade                           object
 9    sub_grade                       object
 10   emp_title                       object
 11   emp_length                      object
 12   home_ownership                  object
 13   annual_inc                      float64
 14   verification_status             object
 15   issue_d                         object
 16   loan_status                     object
 17   pymnt_plan                      object
 18   url                             object
 19   desc                            object
 20   purpose                         object
 21   title                           object
 22   zip_code                        object
 23   addr_state                      object
 24   dti                             float64
 25   delinq_2yrs                     int64
 26   earliest_cr_line                object
 27   inq_last_6mths                  int64
 28   mths_since_last_delinq          float64
 29   mths_since_last_record          float64
 30   open_acc                        int64
 31   pub_rec                         int64
 32   revol_bal                       int64
 33   revol_util                      object
 34   total_acc                       int64
 35   initial_list_status             object
 36   out_prncp                       float64
 37   out_prncp_inv                   float64
 38   total_pymnt                     float64
 39   total_pymnt_inv                 float64
 40   total_rec_prncp                 float64
 41   total_rec_int                   float64
 42   total_rec_late_fee              float64
 43   recoveries                      float64
 44   collection_recovery_fee         float64
 45   last_pymnt_d                    object
 46   last_pymnt_amnt                 float64
 47   next_pymnt_d                    object
 48   last_credit_pull_d              object
 49   collections_12_mths_ex_med      float64
 50   mths_since_last_major_derog     float64
 51   policy_code                     int64
 52   application_type                object
 53   annual_inc_joint                float64
 54   dti_joint                       float64
 55   verification_status_joint       float64
 56   acc_now_delinq                  int64
 57   tot_coll_amt                    float64
 58   tot_cur_bal                     float64
 59   open_acc_6m                     float64
 60   open_il_6m                      float64
 61   open_il_12m                     float64
 62   open_il_24m                     float64
 63   mths_since_rcnt_il              float64
 64   total_bal_il                    float64
 65   il_util                         float64
 66   open_rv_12m                     float64
 67   open_rv_24m                     float64
 68   max_bal_bc                      float64
 69   all_util                        float64
 70   total_rev_hi_lim                float64
 71   inq_fi                          float64
 72   total_cu_tl                     float64
 73   inq_last_12m                    float64
 74   acc_open_past_24mths            float64
 75   avg_cur_bal                     float64
 76   bc_open_to_buy                  float64
 77   bc_util                         float64
 78   chargeoff_within_12_mths        float64
 79   delinq_amnt                     int64
 80   mo_sin_old_il_acct              float64
 81   mo_sin_old_rev_tl_op            float64
 82   mo_sin_rcnt_rev_tl_op           float64
 83   mo_sin_rcnt_tl                  float64
 84   mort_acc                        float64
 85   mths_since_recent_bc            float64
 86   mths_since_recent_bc_dlq        float64
 87   mths_since_recent_inq           float64
 88   mths_since_recent_revol_delinq  float64
 89   num_accts_ever_120_pd           float64
 90   num_actv_bc_tl                  float64
 91   num_actv_rev_tl                 float64
 92   num_bc_sats                     float64
 93   num_bc_tl                       float64
 94   num_il_tl                       float64
 95   num_op_rev_tl                   float64
 96   num_rev_accts                   float64
 97   num_rev_tl_bal_gt_0             float64
 98   num_sats                        float64
 99   num_tl_120dpd_2m                float64
 100  num_tl_30dpd                    float64
 101  num_tl_90g_dpd_24m              float64
 102  num_tl_op_past_12m              float64
 103  pct_tl_nvr_dlq                  float64
 104  percent_bc_gt_75                float64
 105  pub_rec_bankruptcies            float64
 106  tax_liens                       float64
 107  tot_hi_cred_lim                 float64
 108  total_bal_ex_mort               float64
 109  total_bc_limit                  float64
 110  total_il_high_credit_limit      float64
dtypes: float64(74), int64(13), object(24)
memory usage: 33.6+ MB

In [ ]:
# Review the null columns %
round(data.isnull().mean()*100,2)

id                              0.0
member_id                       0.0
loan_amnt                       0.0
funded_amnt                     0.0
funded_amnt_inv                 0.0
                              ...
tax_liens                       0.1
tot_hi_cred_lim               100.0
total_bal_ex_mort             100.0
total_bc_limit                100.0
total_il_high_credit_limit    100.0
Length: 111, dtype: float64

In [ ]:
data['desc'].head()

0      Borrower added on 12/22/11 > I need to upgra...
1      Borrower added on 12/22/11 > I plan to use t...
2                                                  NaN
3      Borrower added on 12/21/11 > to pay for prop...
4      Borrower added on 12/21/11 > I plan on combi...
Name: desc, dtype: object



*   Upon observation, several columns contain 100% missing/null data,rendring then redundant.
*   55 Columns have 100% null values,columns having >75% missing values can be dropped.
*   The desc column can also be dropped since this data is very verbose
*   We can drop this irrelevent columns to streamline the data model.

In [ ]:
columns_to_drop=data.columns[data.isnull().mean()>0.75]
data.shape

data.drop(columns_to_drop,axis=1,inplace=True)
data.shape
data.drop('desc',axis=1,inplace=True)
data.shape

(39717, 54)

##**Post-issuance behavioral features need to be excluded from the features set to prevent Lookahead Bias(Data Leakage.)**


*   **Production Feasibility & Cold Start Problem:** Behavioral metrics are unavailable at the time of credit evaluation for first-time applicants or new borrowers. Relying on post-sanction variables renders the model unusable for real-time loan underwriting.
*   Hence, we can drop such columns which contains customer behavior.

In [ ]:
customer_behavior_columns=['delinq_2yrs','earliest_cr_line', 'inq_last_6mths', 'open_acc', 'pub_rec','revol_bal',
                         'revol_util', 'total_acc', 'out_prncp', 'out_prncp_inv','total_pymnt', 'total_pymnt_inv',
                         'total_rec_prncp', 'total_rec_int','total_rec_late_fee', 'recoveries', 'collection_recovery_fee'
                         ,'last_pymnt_d', 'last_pymnt_amnt', 'last_credit_pull_d','mths_since_last_delinq','id','url',
                         'title']
data = data.drop(customer_behavior_columns, axis=1)
data.shape

(39717, 30)

In [ ]:
data.shape

(39717, 30)

## **Fixing Datatype**

In [ ]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 39717 entries, 0 to 39716
Data columns (total 30 columns):
 #   Column                      Non-Null Count  Dtype
---  ------                      --------------  -----
 0   member_id                   39717 non-null  int64
 1   loan_amnt                   39717 non-null  int64
 2   funded_amnt                 39717 non-null  int64
 3   funded_amnt_inv             39717 non-null  float64
 4   term                        39717 non-null  object
 5   int_rate                    39717 non-null  object
 6   installment                 39717 non-null  float64
 7   grade                       39717 non-null  object
 8   sub_grade                   39717 non-null  object
 9   emp_title                   37258 non-null  object
 10  emp_length                  38642 non-null  object
 11  home_ownership              39717 non-null  object
 12  annual_inc                  39717 non-null  float64
 13  verification_status         39717 non-null  object
 14  issue_d                     39717 non-null  object
 15  loan_status                 39717 non-null  object
 16  pymnt_plan                  39717 non-null  object
 17  purpose                     39717 non-null  object
 18  zip_code                    39717 non-null  object
 19  addr_state                  39717 non-null  object
 20  dti                         39717 non-null  float64
 21  initial_list_status         39717 non-null  object
 22  collections_12_mths_ex_med  39661 non-null  float64
 23  policy_code                 39717 non-null  int64
 24  application_type            39717 non-null  object
 25  acc_now_delinq              39717 non-null  int64
 26  chargeoff_within_12_mths    39661 non-null  float64
 27  delinq_amnt                 39717 non-null  int64
 28  pub_rec_bankruptcies        39020 non-null  float64
 29  tax_liens                   39678 non-null  float64
dtypes: float64(8), int64(6), object(16)
memory usage: 9.1+ MB

In [ ]:
data.nunique().sort_values()

application_type                  1
acc_now_delinq                    1
chargeoff_within_12_mths          1
delinq_amnt                       1
initial_list_status               1
collections_12_mths_ex_med        1
policy_code                       1
tax_liens                         1
pymnt_plan                        1
term                              2
verification_status               3
loan_status                       3
pub_rec_bankruptcies              3
home_ownership                    5
grade                             7
emp_length                       11
purpose                          14
sub_grade                        35
addr_state                       50
issue_d                          55
int_rate                        371
zip_code                        823
loan_amnt                       885
funded_amnt                    1041
dti                            2868
annual_inc                     5318
funded_amnt_inv                8205
installment                   15383
emp_title                     28820
member_id                     39717
dtype: int64



*   **Upon observation, there are columns with low variance.**
*   **Columns with low variance can be dropped to reduce dimensionality.**
*   **We drop low-cardinality/low-variance features because they provide negligible information, increase computational cost, and can lead to overfitting without improving accuracy.**

In [ ]:
for col in data.columns:
  if data[col].nunique()==1:
    data.drop(columns=[col],inplace=True)

In [ ]:
data.nunique().sort_values()

term                        2
loan_status                 3
verification_status         3
pub_rec_bankruptcies        3
home_ownership              5
grade                       7
emp_length                 11
purpose                    14
sub_grade                  35
addr_state                 50
issue_d                    55
int_rate                  371
zip_code                  823
loan_amnt                 885
funded_amnt              1041
dti                      2868
annual_inc               5318
funded_amnt_inv          8205
installment             15383
emp_title               28820
member_id               39717
dtype: int64

In [ ]:
data.shape

(39717, 21)

In [ ]:
data['term'].head(15)

0      36 months
1      60 months
2      36 months
3      36 months
4      60 months
5      36 months
6      60 months
7      36 months
8      60 months
9      60 months
10     60 months
11     36 months
12     36 months
13     36 months
14     36 months
Name: term, dtype: object

In [ ]:
# In column 'term' extra words need to remove
data['term']=data['term'].str.replace("months",'')
data['term'].value_counts()

term
36     29096
60     10621
Name: count, dtype: int64

In [ ]:
data['loan_status'].value_counts()

loan_status
Fully Paid     32950
Charged Off     5627
Current         1140
Name: count, dtype: int64

In [ ]:
data['verification_status'].value_counts()

verification_status
Not Verified       16921
Verified           12809
Source Verified     9987
Name: count, dtype: int64



*   **The loan_status & verification_status features can be retained as-is.**

In [ ]:
data['pub_rec_bankruptcies'].isna()

0        False
1        False
2        False
3        False
4        False
         ...
39712     True
39713     True
39714     True
39715     True
39716     True
Name: pub_rec_bankruptcies, Length: 39717, dtype: bool

In [ ]:
# Filling null values with 0 assuming no previous public record of bankrupt.
data['pub_rec_bankruptcies'].fillna(0)

0        0.0
1        0.0
2        0.0
3        0.0
4        0.0
        ...
39712    0.0
39713    0.0
39714    0.0
39715    0.0
39716    0.0
Name: pub_rec_bankruptcies, Length: 39717, dtype: float64

In [ ]:
data['home_ownership'].value_counts()

home_ownership
RENT        18899
MORTGAGE    17659
OWN          3058
OTHER          98
NONE            3
Name: count, dtype: int64

In [ ]:
data['home_ownership'].isnull().sum()

np.int64(0)

In [ ]:
data['grade'].value_counts()

grade
B    12020
A    10085
C     8098
D     5307
E     2842
F     1049
G      316
Name: count, dtype: int64

In [ ]:
data['grade'].isnull().sum()

np.int64(0)



*   **The home_ownership and grade columns can be retained as is.**

In [ ]:
data['emp_length'].value_counts()

emp_length
10+ years    8879
< 1 year     4583
2 years      4388
3 years      4095
4 years      3436
5 years      3282
1 year       3240
6 years      2229
7 years      1773
8 years      1479
9 years      1258
Name: count, dtype: int64

In [ ]:
# Change the datatype of employe lenth and fixing the cell by removing extra words.

data['emp_length']=data['emp_length'].str.replace('years','')
data['emp_length']=data['emp_length'].str.replace("+",'')
data['emp_length']=data['emp_length'].str.replace("< 1",'0.5')
data['emp_length']=data['emp_length'].str.replace("year",'')

In [ ]:
data['emp_length'].value_counts()

emp_length
10      8879
0.5     4583
2       4388
3       4095
4       3436
5       3282
1       3240
6       2229
7       1773
8       1479
9       1258
Name: count, dtype: int64

In [ ]:
data['purpose'].value_counts()

purpose
debt_consolidation    18641
credit_card            5130
other                  3993
home_improvement       2976
major_purchase         2187
small_business         1828
car                    1549
wedding                 947
medical                 693
moving                  583
vacation                381
house                   381
educational             325
renewable_energy        103
Name: count, dtype: int64

In [ ]:
data['purpose'].isnull().sum()

np.int64(0)

In [ ]:
data['sub_grade'].value_counts()

sub_grade
B3    2917
A4    2886
A5    2742
B5    2704
B4    2512
C1    2136
B2    2057
C2    2011
B1    1830
A3    1810
C3    1529
A2    1508
D2    1348
C4    1236
C5    1186
D3    1173
A1    1139
D4     981
D1     931
D5     874
E1     763
E2     656
E3     553
E4     454
E5     416
F1     329
F2     249
F3     185
F4     168
F5     118
G1     104
G2      78
G4      56
G3      48
G5      30
Name: count, dtype: int64

In [ ]:
data['sub_grade'].isnull().sum()

np.int64(0)

In [ ]:
data['addr_state'].isnull().sum()

np.int64(0)



*   **NO action required for add_state, sub_grade &purpose as they contain clean, valid and predictive data.**

In [ ]:
data['issue_d'].value_counts()

issue_d
Dec-11    2260
Nov-11    2223
Oct-11    2114
Sep-11    2063
Aug-11    1928
Jul-11    1870
Jun-11    1827
May-11    1689
Apr-11    1562
Mar-11    1443
Jan-11    1380
Feb-11    1297
Dec-10    1267
Oct-10    1132
Nov-10    1121
Jul-10    1119
Sep-10    1086
Aug-10    1078
Jun-10    1029
May-10     920
Apr-10     827
Mar-10     737
Feb-10     627
Nov-09     602
Dec-09     598
Jan-10     589
Oct-09     545
Sep-09     449
Aug-09     408
Jul-09     374
Jun-09     356
May-09     319
Apr-09     290
Mar-09     276
Feb-09     260
Jan-09     239
Mar-08     236
Dec-08     223
Nov-08     184
Feb-08     174
Jan-08     171
Apr-08     155
Oct-08      96
Dec-07      85
Jul-08      83
Aug-08      71
May-08      71
Jun-08      66
Oct-07      47
Nov-07      37
Aug-07      33
Sep-08      32
Jul-07      30
Sep-07      18
Jun-07       1
Name: count, dtype: int64

In [ ]:
# Adding year in issue_id in the format
data['issuemonth'] = data['issue_d'].str[:3]+'-2021'

In [ ]:
data.issuemonth.value_counts()

issuemonth
Dec-2021    4433
Nov-2021    4167
Oct-2021    3934
Sep-2021    3648
Aug-2021    3518
Jul-2021    3476
Jun-2021    3279
May-2021    2999
Apr-2021    2834
Mar-2021    2692
Jan-2021    2379
Feb-2021    2358
Name: count, dtype: int64

In [ ]:
data['int_rate'].value_counts()

int_rate
10.99%    956
13.49%    826
11.49%    825
7.51%     787
7.88%     725
         ...
17.34%      1
16.71%      1
16.15%      1
18.36%      1
14.67%      1
Name: count, Length: 371, dtype: int64

In [ ]:
# removing the extra word %
data['int_rate']=data['int_rate'].str.replace("%",'')

In [ ]:
# Change datatype
data['int_rate']=data['int_rate'].astype('float64')

In [ ]:
data['int_rate'].isnull().sum()

np.int64(0)

In [ ]:
data['zip_code'].head()

0    860xx
1    309xx
2    606xx
3    917xx
4    972xx
Name: zip_code, dtype: object

In [ ]:
data['zip_code'].isnull().sum()

np.int64(0)

In [ ]:
data['loan_amnt'].isnull().sum()

np.int64(0)

In [ ]:
data['loan_amnt'].value_counts()

loan_amnt
10000    2833
12000    2334
5000     2051
6000     1908
15000    1895
         ...
18125       1
23050       1
11175       1
21825       1
10475       1
Name: count, Length: 885, dtype: int64

In [ ]:
data['funded_amnt'].isnull().sum()

np.int64(0)

In [ ]:
data['funded_amnt'].value_counts()

funded_amnt
10000    2741
12000    2244
5000     2040
6000     1898
15000    1784
         ...
950         1
700         1
725         1
1175        1
4825        1
Name: count, Length: 1041, dtype: int64

In [ ]:
data['dti'].isnull().sum()

np.int64(0)

In [ ]:
data['dti'].value_counts()

dti
0.00     183
12.00     51
18.00     45
19.20     40
13.20     39
        ...
29.46      1
27.25      1
25.24      1
28.61      1
25.67      1
Name: count, Length: 2868, dtype: int64

In [ ]:
data['dti'].head()

0    27.65
1     1.00
2     8.72
3    20.00
4    17.94
Name: dti, dtype: float64

In [ ]:
data.isnull().sum()

member_id                  0
loan_amnt                  0
funded_amnt                0
funded_amnt_inv            0
term                       0
int_rate                   0
installment                0
grade                      0
sub_grade                  0
emp_title               2459
emp_length              1075
home_ownership             0
annual_inc                 0
verification_status        0
issue_d                    0
loan_status                0
purpose                    0
zip_code                   0
addr_state                 0
dti                        0
pub_rec_bankruptcies     697
issuemonth                 0
dtype: int64

In [ ]:
data['emp_title']=data['emp_title'].fillna('Unknown')

In [ ]:
data['empl_length']=data['emp_length'].fillna(0)

In [ ]:
data['emp_length'].head()

0     10
1    0.5
2     10
3     10
4      1
Name: emp_length, dtype: object



*   **Rest all feilds are not required to change**List item

In [ ]:
# checking the clean dataset
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 39717 entries, 0 to 39716
Data columns (total 23 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   member_id             39717 non-null  int64
 1   loan_amnt             39717 non-null  int64
 2   funded_amnt           39717 non-null  int64
 3   funded_amnt_inv       39717 non-null  float64
 4   term                  39717 non-null  object
 5   int_rate              39717 non-null  float64
 6   installment           39717 non-null  float64
 7   grade                 39717 non-null  object
 8   sub_grade             39717 non-null  object
 9   emp_title             39717 non-null  object
 10  emp_length            38642 non-null  object
 11  home_ownership        39717 non-null  object
 12  annual_inc            39717 non-null  float64
 13  verification_status   39717 non-null  object
 14  issue_d               39717 non-null  object
 15  loan_status           39717 non-null  object
 16  purpose               39717 non-null  object
 17  zip_code              39717 non-null  object
 18  addr_state            39717 non-null  object
 19  dti                   39717 non-null  float64
 20  pub_rec_bankruptcies  39020 non-null  float64
 21  issuemonth            39717 non-null  object
 22  empl_length           39717 non-null  object
dtypes: float64(6), int64(3), object(14)
memory usage: 7.0+ MB

In [ ]:
data.isnull().sum()

member_id                  0
loan_amnt                  0
funded_amnt                0
funded_amnt_inv            0
term                       0
int_rate                   0
installment                0
grade                      0
sub_grade                  0
emp_title                  0
emp_length              1075
home_ownership             0
annual_inc                 0
verification_status        0
issue_d                    0
loan_status                0
purpose                    0
zip_code                   0
addr_state                 0
dti                        0
pub_rec_bankruptcies     697
issuemonth                 0
empl_length                0
dtype: int64

In [ ]:
data['pub_rec_bankruptcies'].head()

0    0.0
1    0.0
2    0.0
3    0.0
4    0.0
Name: pub_rec_bankruptcies, dtype: float64

In [ ]:
data['pub_rec_bankruptcies']=data['pub_rec_bankruptcies'].fillna(0.0)

In [ ]:
data['pub_rec_bankruptcies'].isnull().sum()

np.int64(0)

In [ ]:
data['emp_length']=data['emp_length'].fillna("0")

In [ ]:
data['emp_length'].isnull().sum()

np.int64(0)

In [ ]:
data.isnull().sum()

member_id               0
loan_amnt               0
funded_amnt             0
funded_amnt_inv         0
term                    0
int_rate                0
installment             0
grade                   0
sub_grade               0
emp_title               0
emp_length              0
home_ownership          0
annual_inc              0
verification_status     0
issue_d                 0
loan_status             0
purpose                 0
zip_code                0
addr_state              0
dti                     0
pub_rec_bankruptcies    0
issuemonth              0
empl_length             0
dtype: int64

In [ ]:
data.describe()

,member_id,loan_amnt,funded_amnt,funded_amnt_inv,int_rate,installment,annual_inc,dti,pub_rec_bankruptcies
count,3.971700e+04,39717.000000,39717.000000,39717.000000,39717.000000,39717.000000,3.971700e+04,39717.000000,39717.000000
mean,8.504636e+05,11219.443815,10947.713196,10397.448868,12.021177,324.561922,6.896893e+04,13.315130,0.042501
std,2.656783e+05,7456.670694,7187.238670,7128.450439,3.724825,208.874874,6.379377e+04,6.678594,0.202603
min,7.069900e+04,500.000000,500.000000,0.000000,5.420000,15.690000,4.000000e+03,0.000000,0.000000
25%,6.667800e+05,5500.000000,5400.000000,5000.000000,9.250000,167.020000,4.040400e+04,8.170000,0.000000
50%,8.508120e+05,10000.000000,9600.000000,8975.000000,11.860000,280.220000,5.900000e+04,13.400000,0.000000
75%,1.047339e+06,15000.000000,15000.000000,14400.000000,14.590000,430.780000,8.230000e+04,18.600000,0.000000
max,1.314167e+06,35000.000000,35000.000000,35000.000000,24.590000,1305.190000,6.000000e+06,29.990000,2.000000

In [ ]:
data['member_id'].head()

0    1296599
1    1314167
2    1313524
3    1277178
4    1311748
Name: member_id, dtype: int64

In [ ]:
# member id should be a object
data['member_id']=data['member_id'].astype(object)

In [ ]:
data['member_id'].head()

0    1296599
1    1314167
2    1313524
3    1277178
4    1311748
Name: member_id, dtype: object

In [ ]:
data.describe()

,loan_amnt,funded_amnt,funded_amnt_inv,int_rate,installment,annual_inc,dti,pub_rec_bankruptcies
count,39717.000000,39717.000000,39717.000000,39717.000000,39717.000000,3.971700e+04,39717.000000,39717.000000
mean,11219.443815,10947.713196,10397.448868,12.021177,324.561922,6.896893e+04,13.315130,0.042501
std,7456.670694,7187.238670,7128.450439,3.724825,208.874874,6.379377e+04,6.678594,0.202603
min,500.000000,500.000000,0.000000,5.420000,15.690000,4.000000e+03,0.000000,0.000000
25%,5500.000000,5400.000000,5000.000000,9.250000,167.020000,4.040400e+04,8.170000,0.000000
50%,10000.000000,9600.000000,8975.000000,11.860000,280.220000,5.900000e+04,13.400000,0.000000
75%,15000.000000,15000.000000,14400.000000,14.590000,430.780000,8.230000e+04,18.600000,0.000000
max,35000.000000,35000.000000,35000.000000,24.590000,1305.190000,6.000000e+06,29.990000,2.000000

In [ ]:
data['funded_amnt_inv'].head()

0     4975.0
1     2500.0
2     2400.0
3    10000.0
4     3000.0
Name: funded_amnt_inv, dtype: float64

## **Downloading the cleaned data**

In [ ]:
from google.colab import files
data.to_csv('lending_club_loan_clean_data.csv')
files.download('lending_club_loan_clean_data.csv')